name: RK-OK_graphic-inspiration
favicon: null
layout_spectrum: 0.5525330151431262
typography_spectrum: 0.3576138545759022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6698706599418074
  lightness: 0.4668344941455871
  saturation: 0.5237128206063062
  rhythmicContrast: 0.9224263492505997
purpose: []
