name: RK-OK_graphic-inspiration
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#484349'
    - '#e7d5bd'
    - '#bfae9a'
    - '#666062'
    - '#050004'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
